/* -------- This file has been automatically generated by configure ---------
   Note: Any changes in it will be lost when you run configure again. */

/* Protect against multiple inclusion */
#ifndef __POSTPROC_CONFIG_H__
#define __POSTPROC_CONFIG_H__ 1

// #define ARCH_X86 1

/* Runtime CPU detection */
#define HAVE_MMX
#define HAVE_MMX2

/* Only use during compliation */
#if defined(RUNTIME_CPUDETECT) 
#undef  HAVE_MMX
#define HAVE_MMX
#define HAVE_MMX2
#define HAVE_SSE
#define HAVE_SSE2
#define HAVE_3DNOW
#define HAVE_3DNOWEX
#endif 

/* Use 3dnow/mmxext/sse/mmx optimized fast memcpy() [maybe buggy... signal 4]*/
#define USE_FASTMEMCPY 1

/* Use libswscale */
#define HAVE_SWSCALE

/* attribute(used) as needed by some compilers */
#if (__GNUC__ * 100 + __GNUC_MINOR__ >= 300)
# define attribute_used __attribute__((used))
#else
# define attribute_used
#endif
#endif
