/* -------- This file has been automatically generated by configure ---------
   Note: Any changes in it will be lost when you run configure again. */

/* Protect against multiple inclusion */
#ifndef MPLAYER_CONFIG_H
#define MPLAYER_CONFIG_H 1

/* use GNU internationalization */


/* name of messages charset */
#define MSG_CHARSET "UTF-8"

/* Runtime CPU detection */
#undef RUNTIME_CPUDETECT

/* Dynamic a/v plugins */
#undef DYNAMIC_PLUGINS

/* "restrict" keyword */
#define restrict __restrict

/* __builtin_expect branch prediction hint */
#define HAVE_BUILTIN_EXPECT 1
#ifdef HAVE_BUILTIN_EXPECT
#define likely(x) __builtin_expect ((x) != 0, 1)
#define unlikely(x) __builtin_expect ((x) != 0, 0)
#else
#define likely(x) (x)
#define unlikely(x) (x)
#endif

/* attribute(used) as needed by some compilers */
#if (__GNUC__ * 100 + __GNUC_MINOR__ >= 300)
# define attribute_used __attribute__((used))
#else
# define attribute_used
#endif

#define PREFIX "/usr/local"

#define USE_OSD 1
#define USE_SUB 1

/* enable/disable SIGHANDLER */
#define ENABLE_SIGHANDLER 1

/* enable/disable automatic gdb attach on crash, requires SIGHANDLER */
#undef CRASH_DEBUG

/* Toggles debugging informations */
#undef MP_DEBUG

/* Toggles colorized output */
//#define MSG_USE_COLORS 1

/* Indicates that libcdio is available for VCD and CD-DA playback */
#undef HAVE_LIBCDIO

/* Indicates that Ogle's libdvdread is available for DVD playback */
#define USE_DVDREAD 1

/* Indicates that dvdread is from libmpdvdkit */
#define USE_MPDVDKIT 2

/* Additional options for libmpdvdkit*/
#undef DVD_STRUCT_IN_DVD_H
#define DVD_STRUCT_IN_LINUX_CDROM_H 1
#undef DVD_STRUCT_IN_SYS_CDIO_H
#undef DVD_STRUCT_IN_SYS_DVDIO_H
#undef DVD_STRUCT_IN_BSDI_DVDIOCTL_DVD_H
#undef HAVE_BSD_DVD_STRUCT
#define HAVE_LINUX_DVD_STRUCT 1
#undef HAVE_OPENBSD_DVD_STRUCT
#undef DARWIN_DVD_IOCTL
#undef SOLARIS_USCSI
#undef HPUX_SCTL_IO
#define HAVE_STDDEF_H 1
#define HAVE_DVD 1

/* Common data directory (for fonts, etc) */
#define MPLAYER_DATADIR "/usr/local/share/mplayer"
#define MPLAYER_CONFDIR "/usr/local/etc/mplayer"
#define MPLAYER_LIBDIR "/usr/local/lib"

/* Define this to compile stream-caching support, it can be enabled via
   -cache <kilobytes> */
#define USE_STREAM_CACHE 1

/* Define to include support for XviD/Divx4Linux/OpenDivx */
#undef USE_DIVX

/* Define to use the new XviD/DivX4Linux library instead of open source OpenDivX */
/* You have to change DECORE_LIBS in config.mak, too! */
#undef NEW_DECORE

/* Define if you are using DivX5Linux Decore library */
#undef DECORE_DIVX5

/* Define if you are using XviD library */
#undef HAVE_XVID3
#define HAVE_XVID4 1
#undef DECORE_XVID
#undef ENCORE_XVID

/* Define if you are using the X.264 library */
#undef HAVE_X264

/* Define to include support for libdv-0.9.5 */
#define HAVE_LIBDV095 1

/* If build mencoder */
#define HAVE_MENCODER

/* Indicates if XviD/Divx4linux encore is available
   Note: for mencoder */
#undef HAVE_DIVX4ENCORE

/* Indicates if libmp3lame is available
   Note: for mencoder */
#define HAVE_MP3LAME
#define HAVE_MP3LAME_PRESET
#define HAVE_MP3LAME_PRESET_MEDIUM

/* Define libmp1e for realtime mpeg encoding (for DXR3 and DVB cards) */
#undef USE_MP1E

/* Define this to enable avg. byte/sec-based AVI sync method by default:
   (use -bps or -nobps commandline option for run-time method selection)
   -bps gives better sync for vbr mp3 audio, it is now default */
#define AVI_SYNC_BPS 1

/* Undefine this if you do not want to select mono audio (left or right)
   with a stereo MPEG layer 2/3 audio stream. The command line option
   -stereo has three possible values (0 for stereo, 1 for left-only, 2 for
   right-only), with 0 being the default.
   */
#define USE_FAKE_MONO 1

/* Undefine this if your sound card driver has no working select().
   If you have kernel Oops, player hangups, or just no audio, you should
   try to recompile MPlayer with this option disabled! */
#define HAVE_AUDIO_SELECT 1

/* define this to use iconv(3) function to codepage conversions */
#define USE_ICONV 1

/* define this to use nl_langinfo function */
#define USE_LANGINFO 1

/* define this to use RTC (/dev/rtc) for video timers */
#define HAVE_RTC 1

/* set up max. outburst. use 65536 for ALSA 0.5, for others 16384 is enough */
#define MAX_OUTBURST 65536

/* set up audio OUTBURST. Do not change this! */
#define OUTBURST 512

/* Define this if your system has the header file for the OSS sound interface */
#define HAVE_SYS_SOUNDCARD_H 1

/* Define this if your system has the header file for the OSS sound interface
 * in /usr/include */
#undef HAVE_SOUNDCARD_H

/* Define this if your system has the sysinfo header */
#define HAVE_SYS_SYSINFO_H 1

/* Define this if your system has ftello() */

#define HAVE_FTELLO 1
#ifndef HAVE_FTELLO
/* Need these for FILE and off_t an config.h is usually before other includes*/
#include <stdio.h>
#include <sys/types.h>
off_t ftello(FILE *);
#endif

/* Define this if your system has the "malloc.h" header file */
#define HAVE_MALLOC_H 1

/* memalign is mapped to malloc if unsupported */
#define HAVE_MEMALIGN 1
#ifndef HAVE_MEMALIGN
# define memalign(a,b) malloc(b)
#define MEMALIGN_HACK 1
#endif

/* Define this if your system has the "alloca.h" header file */
#define HAVE_ALLOCA_H 1

/* Define this if your system has the "sys/mman.h" header file */
#define HAVE_SYS_MMAN_H 1


/* Define this if you have the elf dynamic linker -ldl library */
#define HAVE_LIBDL 1

/* Define this if you have the kstat kernel statistics library */
#undef HAVE_LIBKSTAT

/* Define this if you have zlib */
#define HAVE_ZLIB 1
#ifdef HAVE_ZLIB
#define CONFIG_ZLIB 1
#endif

/* Define this if you have shm support */
#define HAVE_SHM 1

/* Define this if your system has scandir & alphasort */
#define HAVE_SCANDIR 1

/* Define this if your system has strsep */
#define HAVE_STRSEP 1

/* Define this if your system has strlcpy */
#undef HAVE_STRLCPY
#ifndef HAVE_STRLCPY
unsigned int strlcpy (char *dest, const char *src, unsigned int size);
#endif

/* Define this if your system has strlcat */
#undef HAVE_STRLCAT
#ifndef HAVE_STRLCAT
unsigned int strlcat (char *dest, const char *src, unsigned int size);
#endif

/* Define this if your system has fseeko */
#define HAVE_FSEEKO 1
#ifndef HAVE_FSEEKO
/* Need these for FILE and off_t an config.h is usually before other includes*/
#include <stdio.h>
#include <sys/types.h>
int fseeko(FILE *, off_t, int);
#endif

#define HAVE_LOCALTIME_R 1

/* Define this if your system has vsscanf */
#define HAVE_VSSCANF 1

/* Define this if your system has swab */
#define HAVE_SWAB 1

/* Define this if your system has no posix select */
#undef HAVE_NO_POSIX_SELECT

/* Define this if your system has gettimeofday */
#define HAVE_GETTIMEOFDAY 1

/* Define this if your system has glob */
#define HAVE_GLOB 1

/* Define this if your system has setenv */
#define HAVE_SETENV 1
#ifndef HAVE_SETENV
int setenv(const char *name, const char *val, int overwrite);
#endif

/* Define this if your system has sysi86 */


/* Define this if your system has pthreads */
#define HAVE_PTHREADS 1

/* Define this if you enabled thread support for libavcodec */
#define HAVE_THREADS 1

/* LIRC (remote control, see www.lirc.org) support: */
#undef HAVE_LIRC

/*
 * LIRCCD (LIRC client daemon)
 * See http://www.dolda2000.cjb.net/~fredrik/lirccd/
 */
#undef HAVE_LIRCC

/* DVD navigation support using libdvdnav */



/* Define this to enable MPEG 1/2 image postprocessing (requires a FAST CPU!) */
#define MPEG12_POSTPROC 1

/* Define this to enable image postprocessing in libavcodec (requires a FAST CPU!) */
#define USE_LIBPOSTPROC 1
#undef USE_LIBPOSTPROC_SO

/* Define to include support for OpenDivx postprocessing */
#undef HAVE_ODIVX_POSTPROCESS

/* Win32 DLL support */
#undef USE_WIN32DLL
#define WIN32_PATH ""

/* DirectShow support */
#undef USE_DIRECTSHOW

/* Mac OS X specific features */

#undef MACOSX_FINDER_SUPPORT
#undef MACOSX_BUNDLE


/* Build our Win32-loader */


/* ffmpeg's libavcodec support (requires libavcodec source) */
#define USE_LIBAVCODEC 1
#undef USE_LIBAVCODEC_SO
#define USE_LIBAVCODEC_DSPUTIL

/* ffmpeg's libavformat support (requires libavformat source) */
#define USE_LIBAVFORMAT 1
#undef USE_LIBAVFORMAT_SO
#undef CONFIG_WIN32

/* Use libavcodec's decoders */
#define CONFIG_DECODERS 1
/* Use libavcodec's encoders */
#define CONFIG_ENCODERS 1

/* Use libavformat's demuxers */
#define CONFIG_DEMUXERS 1
/* Use libavformat's muxers */
#define CONFIG_MUXERS 1

#define CONFIG_MPEGAUDIO_HP 1

#define CONFIG_GPL 1

/* Use amr codecs from libavcodec (requires amr sources) */

#undef AMR_NB
#undef AMR_NB_FIXED
#undef AMR_WB

/* Use specific codecs from libavcodec */
#define CONFIG_AC3_ENCODER 1
#define CONFIG_MP2_ENCODER 1
#define CONFIG_MP3LAME_ENCODER 1
#define CONFIG_OGGVORBIS_ENCODER 1
#define CONFIG_OGGVORBIS_DECODER 1
#define CONFIG_OGGTHEORA_ENCODER 1
#define CONFIG_OGGTHEORA_DECODER 1
#define CONFIG_FAAC_ENCODER 1
#define CONFIG_XVID_ENCODER 1
#define CONFIG_MPEG1VIDEO_ENCODER 1
#define CONFIG_H264_ENCODER 1
#define CONFIG_MPEG2VIDEO_ENCODER 1
#define CONFIG_H261_ENCODER 1
#define CONFIG_H263_ENCODER 1
#define CONFIG_H263P_ENCODER 1
#define CONFIG_FLV_ENCODER 1
#define CONFIG_RV10_ENCODER 1
#define CONFIG_RV20_ENCODER 1
#define CONFIG_MPEG4_ENCODER 1
#define CONFIG_MSMPEG4V1_ENCODER 1
#define CONFIG_MSMPEG4V2_ENCODER 1
#define CONFIG_MSMPEG4V3_ENCODER 1
#define CONFIG_WMV1_ENCODER 1
#define CONFIG_WMV2_ENCODER 1
#define CONFIG_SVQ1_ENCODER 1
#define CONFIG_MJPEG_ENCODER 1
#define CONFIG_LJPEG_ENCODER 1
#define CONFIG_JPEGLS_ENCODER 1
#define CONFIG_PNG_ENCODER 1
#define CONFIG_PPM_ENCODER 1
#define CONFIG_PGM_ENCODER 1
#define CONFIG_PGMYUV_ENCODER 1
#define CONFIG_PBM_ENCODER 1
#define CONFIG_PAM_ENCODER 1
#define CONFIG_HUFFYUV_ENCODER 1
#define CONFIG_FFVHUFF_ENCODER 1
#define CONFIG_ASV1_ENCODER 1
#define CONFIG_ASV2_ENCODER 1
#define CONFIG_FFV1_ENCODER 1
#define CONFIG_SNOW_ENCODER 1
#define CONFIG_ZLIB_ENCODER 1
#define CONFIG_DVVIDEO_ENCODER 1
#define CONFIG_SONIC_ENCODER 1
#define CONFIG_SONIC_LS_ENCODER 1
#define CONFIG_X264_ENCODER 1
#define CONFIG_LIBGSM_ENCODER 1
#define CONFIG_RAWVIDEO_ENCODER 1
#define CONFIG_H263_DECODER 1
#define CONFIG_H261_DECODER 1
#define CONFIG_MPEG4_DECODER 1
#define CONFIG_MSMPEG4V1_DECODER 1
#define CONFIG_MSMPEG4V2_DECODER 1
#define CONFIG_MSMPEG4V3_DECODER 1
#define CONFIG_WMV1_DECODER 1
#define CONFIG_WMV2_DECODER 1
#define CONFIG_VC9_DECODER 1
#define CONFIG_WMV3_DECODER 1
#define CONFIG_H263I_DECODER 1
#define CONFIG_FLV_DECODER 1
#define CONFIG_RV10_DECODER 1
#define CONFIG_RV20_DECODER 1
#define CONFIG_SVQ1_DECODER 1
#define CONFIG_SVQ3_DECODER 1
#define CONFIG_WMAV1_DECODER 1
#define CONFIG_WMAV2_DECODER 1
#define CONFIG_INDEO2_DECODER 1
#define CONFIG_INDEO3_DECODER 1
#define CONFIG_TSCC_DECODER 1
#define CONFIG_CSCD_DECODER 1
#define CONFIG_NUV_DECODER 1
#define CONFIG_ULTI_DECODER 1
#define CONFIG_QDRAW_DECODER 1
#define CONFIG_XL_DECODER 1
#define CONFIG_QPEG_DECODER 1
#define CONFIG_LOCO_DECODER 1
#define CONFIG_KMVC_DECODER 1
#define CONFIG_WNV1_DECODER 1
#define CONFIG_AASC_DECODER 1
#define CONFIG_FRAPS_DECODER 1
#define CONFIG_AAC_DECODER 1
#define CONFIG_MPEG4AAC_DECODER 1
#define CONFIG_MPEG1VIDEO_DECODER 1
#define CONFIG_MPEG2VIDEO_DECODER 1
#define CONFIG_MPEGVIDEO_DECODER 1
#define CONFIG_MPEG_XVMC_DECODER 1
#define CONFIG_DVVIDEO_DECODER 1
#define CONFIG_MJPEG_DECODER 1
#define CONFIG_MJPEGB_DECODER 1
#define CONFIG_SP5X_DECODER 1
#define CONFIG_PNG_DECODER 1
#define CONFIG_MP2_DECODER 1
#define CONFIG_MP3_DECODER 1
#define CONFIG_MP3ADU_DECODER 1
#define CONFIG_MP3ON4_DECODER 1
#define CONFIG_MACE3_DECODER 1
#define CONFIG_MACE6_DECODER 1
#define CONFIG_HUFFYUV_DECODER 1
#define CONFIG_FFVHUFF_DECODER 1
#define CONFIG_FFV1_DECODER 1
#define CONFIG_SNOW_DECODER 1
#define CONFIG_CYUV_DECODER 1
#define CONFIG_H264_DECODER 1
#define CONFIG_VP3_DECODER 1
#define CONFIG_THEORA_DECODER 1
#define CONFIG_ASV1_DECODER 1
#define CONFIG_ASV2_DECODER 1
#define CONFIG_VCR1_DECODER 1
#define CONFIG_CLJR_DECODER 1
#define CONFIG_FOURXM_DECODER 1
#define CONFIG_MDEC_DECODER 1
#define CONFIG_ROQ_DECODER 1
#define CONFIG_INTERPLAY_VIDEO_DECODER 1
#define CONFIG_XAN_WC3_DECODER 1
#define CONFIG_RPZA_DECODER 1
#define CONFIG_CINEPAK_DECODER 1
#define CONFIG_MSRLE_DECODER 1
#define CONFIG_MSVIDEO1_DECODER 1
#define CONFIG_VQA_DECODER 1
#define CONFIG_IDCIN_DECODER 1
#define CONFIG_EIGHTBPS_DECODER 1
#define CONFIG_SMC_DECODER 1
#define CONFIG_FLIC_DECODER 1
#define CONFIG_TRUEMOTION1_DECODER 1
#define CONFIG_TRUEMOTION2_DECODER 1
#define CONFIG_VMDVIDEO_DECODER 1
#define CONFIG_VMDAUDIO_DECODER 1
#define CONFIG_MSZH_DECODER 1
#define CONFIG_ZLIB_DECODER 1
#define CONFIG_ZMBV_DECODER 1
#define CONFIG_SMACKER_DECODER 1
#define CONFIG_SMACKAUD_DECODER 1
#define CONFIG_SONIC_DECODER 1
#define CONFIG_AC3_DECODER 1
#define CONFIG_DTS_DECODER 1
#define CONFIG_RA_144_DECODER 1
#define CONFIG_RA_288_DECODER 1
#define CONFIG_ROQ_DPCM_DECODER 1
#define CONFIG_INTERPLAY_DPCM_DECODER 1
#define CONFIG_XAN_DPCM_DECODER 1
#define CONFIG_SOL_DPCM_DECODER 1
#define CONFIG_QTRLE_DECODER 1
#define CONFIG_FLAC_DECODER 1
#define CONFIG_SHORTEN_DECODER 1
#define CONFIG_ALAC_DECODER 1
#define CONFIG_WS_SND1_DECODER 1
#define CONFIG_VORBIS_DECODER 1
#define CONFIG_LIBGSM_DECODER 1
#define CONFIG_QDM2_DECODER 1
#define CONFIG_COOK_DECODER 1
#define CONFIG_TRUESPEECH_DECODER 1
#define CONFIG_TTA_DECODER 1
#define CONFIG_AVS_DECODER 1
#define CONFIG_RAWVIDEO_DECODER 1
#define CONFIG_FLASHSV_DECODER 1
#define CONFIG_AMR_NB_DECODER 1
#define CONFIG_AMR_NB_ENCODER 1
#define CONFIG_AMR_WB_DECODER 1
#define CONFIG_AMR_WB_ENCODER 1
#define CONFIG_BMP_DECODER 1
#define CONFIG_MMVIDEO_DECODER 1
#define CONFIG_DVDSUB_DECODER 1
#define CONFIG_DVDSUB_ENCODER 1
#define CONFIG_DVBSUB_DECODER 1
#define CONFIG_DVBSUB_ENCODER 1
#define CONFIG_FAAC 1
#define CONFIG_XVID 1
#define CONFIG_MP3LAME 1

/* Use codec libs included in mplayer CVS / source dist: */
#define USE_MP3LIB 1
#define USE_LIBA52 1
#define CONFIG_DTS 1
#define USE_LIBMPEG2 1

/* Use libfame encoder filter */
#undef USE_LIBFAME

/* XAnim DLL support */
#undef USE_XANIM
/* Default search path */
#undef XACODEC_PATH

/* RealPlayer DLL support */
#undef USE_REALCODECS
/* Default search path */
#undef REALCODEC_PATH

/* LIVE555 Streaming Media library support */
#undef STREAMING_LIVE555

/* Use 3dnow/mmxext/sse/mmx optimized fast memcpy() [maybe buggy... signal 4]*/
#define USE_FASTMEMCPY 1

/* Use unrarlib for Vobsubs */
#define USE_UNRARLIB 1

/* gui support, please do not edit this option */
#undef HAVE_NEW_GUI
#undef HAVE_GTK2_GUI

/* Audio output drivers */
#define USE_OSS_AUDIO 1
#define PATH_DEV_DSP "/dev/dsp"
#define PATH_DEV_MIXER "/dev/mixer"
#undef HAVE_ALSA5
#undef HAVE_ALSA9
#define HAVE_ALSA1X 1
#define USE_ARTS 1
#define USE_ESD 1
#define HAVE_ESD_LATENCY
#undef USE_POLYP


#undef HAVE_SYS_ASOUNDLIB_H
#define HAVE_ALSA_ASOUNDLIB_H 1
#undef USE_SUN_AUDIO
#undef USE_SGI_AUDIO
#undef HAVE_WIN32WAVEOUT
#define HAVE_NAS 1

/* Enable fast OSD/SUB renderer (looks ugly, but uses less CPU power) */
#undef FAST_OSD
#undef FAST_OSD_TABLE

/* Enable TV Interface support */
#define USE_TV 1

/* Enable Video 4 Linux TV interface support */
#define HAVE_TV_V4L 1

/* Enable Video 4 Linux 2 TV interface support */
#define HAVE_TV_V4L2 1

/* Enable *BSD BrookTree TV interface support */
#undef HAVE_TV_BSDBT848

/* Define if your processor stores words with the most significant
   byte first (like Motorola and SPARC, unlike Intel and VAX).  */
#undef WORDS_BIGENDIAN

#define ARCH_X86 1

/* For the PPC.  G5 has the dcbzl when in 64bit mode but G4s and earlier do not
   have the instruction. */


/* libmpeg2 wants ARCH_PPC and the rest of mplayer use ARCH_POWERPC,
 * define ARCH_PPC if ARCH_POWERPC is set to cope with that.
 */
#ifdef ARCH_POWERPC
#define ARCH_PPC 1
#endif

/* the same issue as with ARCH_POWERPC but with ffmpeg/libavcodec */
#ifdef ARCH_ARMV4L
#define ARCH_ARM 1
#endif

/* only gcc3 can compile mvi instructions */


/* Define this for Cygwin build for win32 */


/* Define this to any prefered value from 386 up to infinity with step 100 */
#define __CPU__ 686

#define MP_WORDSIZE 32

#define TARGET_LINUX 1

#define HAVE_VCD 1

#ifdef sun
#define	DEFAULT_CDROM_DEVICE	"/vol/dev/aliases/cdrom0"
#define DEFAULT_DVD_DEVICE	DEFAULT_CDROM_DEVICE
#elif defined(HPUX)
#define DEFAULT_CDROM_DEVICE    "/dev/cdrom"
#define DEFAULT_DVD_DEVICE     "/dev/dvd"
#elif defined(WIN32)
#define DEFAULT_CDROM_DEVICE    "D:"
#define DEFAULT_DVD_DEVICE	"D:"
#elif defined(SYS_DARWIN)
#define DEFAULT_CDROM_DEVICE    "/dev/disk1"
#define DEFAULT_DVD_DEVICE	"/dev/rdiskN"
#elif defined(__OpenBSD__)
#define DEFAULT_CDROM_DEVICE	"/dev/rcd0a"
#define DEFAULT_DVD_DEVICE	DEFAULT_CDROM_DEVICE
#elif defined(__FreeBSD__)
#define DEFAULT_CDROM_DEVICE	"/dev/acd0"
#define DEFAULT_DVD_DEVICE	DEFAULT_CDROM_DEVICE
#else
#define DEFAULT_CDROM_DEVICE    "/dev/cdrom"
#define DEFAULT_DVD_DEVICE	"/dev/dvd"
#endif


/*----------------------------------------------------------------------------
**
** NOTE: Instead of modifying these definitions here, use the
**       --enable/--disable options of the ./configure script!
**       See ./configure --help for details.
**
*---------------------------------------------------------------------------*/

/* C99 lrintf function available */
#define HAVE_LRINTF 1

/* round function is available */
#define HAVE_ROUND 1

/* yes, we have inttypes.h */
#define HAVE_INTTYPES_H 1

/* int_fastXY_t emulation */


/* nanosleep support */
#define HAVE_NANOSLEEP 1

/* SMB support */
#undef LIBSMBCLIENT

/* termcap flag for getch2.c */
#define USE_TERMCAP 1

/* termios flag for getch2.c */
#define HAVE_TERMIOS 1
#undef HAVE_TERMIOS_H
#define HAVE_SYS_TERMIOS_H 1

/* enable PNG support */
#define HAVE_PNG 1

/* enable JPEG support */
#define HAVE_JPEG 1

/* enable PNM support */
#define HAVE_PNM

/* enable md5sum support */
#define HAVE_MD5SUM

/* enable GIF support */
#undef HAVE_GIF
#undef HAVE_GIF_4


/* enable FreeType support */
#define HAVE_FREETYPE

/* enable Fontconfig support */
#define HAVE_FONTCONFIG

/* enable FriBiDi usage */
#undef USE_FRIBIDI

/* enable ENCA usage */
#undef HAVE_ENCA

/* liblzo support */
#undef USE_LIBLZO
#ifdef USE_LIBLZO
#define CONFIG_LZO 1
#endif

/* libmad support */
#define USE_LIBMAD 1

/* enable OggVorbis support */
#define HAVE_OGGVORBIS 1

/* enable Tremor as vorbis decoder */
#define TREMOR 1

/* enable Speex support */
#define HAVE_SPEEX 1

/* enable musepack support */
#undef HAVE_MUSEPACK

/* enable OggTheora support */
#define HAVE_OGGTHEORA 1

/* enable FAAD (AAC) support */
#define HAVE_FAAD 1
#define USE_INTERNAL_FAAD 1

/* enable FAAC (AAC encoder) support */
#define HAVE_FAAC 1

/* enable LADSPA plugin support */
#undef HAVE_LADSPA

/* enable network */
#define MPLAYER_NETWORK 1

/* enable ftp support */
#define HAVE_FTP 1

/* enable vstream support */
#undef HAVE_VSTREAM

/* enable winsock2 instead of Unix functions*/
#undef HAVE_WINSOCK2

/* define this to use inet_aton() instead of inet_pton() */
#undef USE_ATON

/* enables / disables cdparanoia support */
#define HAVE_CDDA

/* enables / disables VIDIX usage */
#define CONFIG_VIDIX 1
#define MP_VIDIX_PFX "/usr/local/lib" "/mplayer/vidix/" 

/* enables / disables new input joystick support */
#undef HAVE_JOYSTICK

/* enables / disables QTX codecs */
#undef USE_QTX_CODECS

/* enables / disables osd menu */
#undef HAVE_MENU

/* enables / disables subtitles sorting */
#define USE_SORTSUB 1

/* XMMS input plugin support */
#undef HAVE_XMMS
#define XMMS_INPUT_PLUGIN_DIR ""

/* enables inet6 support */
#define HAVE_AF_INET6 1

/* do we have gethostbyname2? */
#define HAVE_GETHOSTBYNAME2 1

/* Extension defines */
#undef HAVE_3DNOW	// only define if you have 3DNOW (AMD k6-2, AMD Athlon, iDT WinChip, etc.)
#undef HAVE_3DNOWEX	// only define if you have 3DNOWEXT (AMD Athlon, etc.)
#define HAVE_MMX 1	// only define if you have MMX (newer x86 chips, not P54C/PPro)
#define HAVE_MMX2 1	// only define if you have MMX2 (Athlon/PIII/4/CelII)
#define HAVE_SSE 1	// only define if you have SSE (Intel Pentium III/4 or Celeron II)
#define HAVE_SSE2 1	// only define if you have SSE2 (Intel Pentium 4)
	// only define if you have Altivec (G4)

	// enables usage of altivec.h

#define HAVE_BUILTIN_VECTOR 1  // enables usage of xmmintrin.h
         // enables usage of mm3dnow.h

#undef HAVE_MLIB  // Sun mediaLib, available only on solaris
	// only define if you have VIS ( ultrasparc )

/* libmpeg2 uses a different feature test macro for mediaLib */
#ifdef HAVE_MLIB
#define LIBMPEG2_MLIB 1
#endif

/* libvo options */
#define SCREEN_SIZE_X 1
#define SCREEN_SIZE_Y 1
#define HAVE_X11 1
#define HAVE_XV 1
#undef HAVE_XVMC
#define HAVE_XF86VM 1
#define HAVE_XF86XK 1
#define HAVE_XINERAMA 1
#define HAVE_GL 1

#undef HAVE_DGA
#undef HAVE_DGA2
#define HAVE_SDL 1
/* defined for SDLlib with keyrepeat bugs (before 1.2.1) */
#undef BUGGY_SDL
#undef HAVE_DIRECTX
#undef HAVE_GGI
#undef HAVE_GGIWMH
#undef HAVE_3DFX
#undef HAVE_S3FB
#undef HAVE_TDFXFB
#undef HAVE_TDFX_VID
#define HAVE_DIRECTFB 1
#define DIRECTFBVERSION 922
#undef HAVE_ZR
#undef HAVE_BL
#undef HAVE_MGA
#undef HAVE_XMGA

#define HAVE_FBDEV 1
#undef HAVE_DXR2
#undef HAVE_DXR3
#define HAVE_DVB_HEAD 1
#define HAS_DVBIN_SUPPORT 1
#undef HAVE_SVGALIB
#undef HAVE_VESA
#define HAVE_XDPMS 1
#define HAVE_AA 1
#define HAVE_CACA 1
#define HAVE_TGA 1
#undef HAVE_TOOLAME
#undef HAVE_TWOLAME

/* used by GUI: */


#if defined(HAVE_GL) || defined(HAVE_X11) || defined(HAVE_XV)
#define X11_FULLSCREEN 1
#endif

#endif /* MPLAYER_CONFIG_H */
